database:
  type: "sqlite" #sqlite, mysql
  mysql:
    address: "135.148.84.216:3306"
    username: "u13_XwvhaD2F1V"
    password: "DqQSNsn+^=UNGz8CDrBVgMax"
    database: "s13_factions"
  sqlite:
    file: "mobcoins.sql"

Settings:
  AdminPermission: 'mobcoins.admin'

KillMob:
  PIG: 5.0
  WOLF: 5.0
  COW: 5.0
  SHEEP: 5.0
  SPIDER: 10.0
  CAVE_SPIDER: 10.0
  ZOMBIE: 20.0
  SKELETON: 20.0
  BLAZE: 30.0
  PIG_ZOMBIE: 10.0
  IRON_GOLEM: 40.0
  VILLAGER: 40.0
  WITCH: 40.0
  WITHER: 50.0

Locais: {}