database:
  type: "sqlite" #sqlite, mysql
  mysql:
    address: "135.148.84.216:3306"
    username: "u13_XwvhaD2F1V"
    password: "DqQSNsn+^=UNGz8CDrBVgMax"
    database: "s13_factions"
  sqlite:
    file: "mobcoins.sql"

Settings:
  AdminPermission: 'mobcoins.admin'

Configuration:
  Entity:
    - 'COW,5.0'
    - 'SHEEP,5.0'


Locais: {}